# Generated by Django 5.2.7 on 2026-02-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_reservation_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
    ]
